
require("./NintexTasks.module.css");
const styles = {
  nintexTasks: 'nintexTasks_a523dc3c',
  teams: 'teams_a523dc3c',
  container: 'container_a523dc3c',
  headerContainer: 'headerContainer_a523dc3c',
  headerTitle: 'headerTitle_a523dc3c',
  toolbarContainer: 'toolbarContainer_a523dc3c',
  toolbarFilters: 'toolbarFilters_a523dc3c',
  statusDropdown: 'statusDropdown_a523dc3c',
  dateDropdown: 'dateDropdown_a523dc3c',
  dateRangePickerContainer: 'dateRangePickerContainer_a523dc3c',
  dateRangeText: 'dateRangeText_a523dc3c',
  calendarIcon: 'calendarIcon_a523dc3c',
  spacer: 'spacer_a523dc3c',
  searchLabel: 'searchLabel_a523dc3c',
  searchStack: 'searchStack_a523dc3c',
  searchBox: 'searchBox_a523dc3c',
  refreshButton: 'refreshButton_a523dc3c',
  errorBar: 'errorBar_a523dc3c',
  loadingContainer: 'loadingContainer_a523dc3c',
  emptyState: 'emptyState_a523dc3c',
  emptyIcon: 'emptyIcon_a523dc3c',
  emptySubtext: 'emptySubtext_a523dc3c',
  listContainer: 'listContainer_a523dc3c',
  paginationBar: 'paginationBar_a523dc3c',
  paginationContent: 'paginationContent_a523dc3c',
  pageInfo: 'pageInfo_a523dc3c',
  paginationButton: 'paginationButton_a523dc3c',
  taskList: 'taskList_a523dc3c',
  taskName: 'taskName_a523dc3c',
  taskNameLink: 'taskNameLink_a523dc3c',
  cellText: 'cellText_a523dc3c',
  statusBadgeOutline: 'statusBadgeOutline_a523dc3c',
  statusActiveOutline: 'statusActiveOutline_a523dc3c',
  statusCompleteOutline: 'statusCompleteOutline_a523dc3c',
  statusExpiredOutline: 'statusExpiredOutline_a523dc3c',
  statusTerminatedOutline: 'statusTerminatedOutline_a523dc3c',
  statusOverriddenOutline: 'statusOverriddenOutline_a523dc3c',
  overdue: 'overdue_a523dc3c',
  detailPanel: 'detailPanel_a523dc3c',
  detailContent: 'detailContent_a523dc3c',
  detailTitle: 'detailTitle_a523dc3c',
  statusIcon: 'statusIcon_a523dc3c',
  statusActive: 'statusActive_a523dc3c',
  statusCompleted: 'statusCompleted_a523dc3c',
  statusExpired: 'statusExpired_a523dc3c',
  detailField: 'detailField_a523dc3c',
  detailLabel: 'detailLabel_a523dc3c',
  detailValue: 'detailValue_a523dc3c',
  formLink: 'formLink_a523dc3c',
  dateFilterCallout: 'dateFilterCallout_a523dc3c',
  segmentedControl: 'segmentedControl_a523dc3c',
  segmentButton: 'segmentButton_a523dc3c',
  segmentActive: 'segmentActive_a523dc3c',
  presetList: 'presetList_a523dc3c',
  presetOption: 'presetOption_a523dc3c',
  presetSelected: 'presetSelected_a523dc3c',
  customDateContainer: 'customDateContainer_a523dc3c',
  delegateRowButton: 'delegateRowButton_a523dc3c'
};

export default styles;
